name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  owner:
    description: 'owner of the target repository'
    required: true
    default: 'betrybe'
  repo:
    description: 'target repository name'
    required: true
  ref:
    description: 'target branch'
    required: true
    default: 'main'
  token:
    description: 'token with credentials to commit in repository'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
