name: 'API Documentation Action'
description: 'Generate API Documentation'
inputs:
  owner:
    description: 'owner of the target repository'
    required: true
    default: 'betrybe'
  repo:
    description: 'target repository name'
    required: true
  ref:
    description: 'target branch'
    required: true
    default: 'main'
  token:
    description: 'token with credentials to commit in repository'
    required: true
  targetOwner:
    description: 'owner of the target repository to dispatch'
    required: true
    default: 'betrybe'
  targetRepo:
    description: 'target repository name  to dispatch'
    required: true
  targetRef:
    description: 'target branch to dispatch'
    required: true
    default: 'main'
  targetWorkflowId:
    description: 'workflow id or workflow filename'
    required: true
    default: 'main.yml'
  themeVariables:
    description: 'theme used to generate the documentation'
    required: false
    default: 'default'
  themeTemplate:
    description: 'Number of columns used in the theme' 
    required: false
    default: 'default'

runs:
  using: 'node16'
  main: 'dist/index.js'
